index:
    path: /
    controller: App\Controller\BookController::homepage

book_view:
    path: /book/{slug}
    controller: App\Controller\BookController::show

book_list:
    path: /admin/book/list
    controller: App\Controller\BookAdminController::list

new_book:
    path: admin/book/new
    controller: App\Controller\BookAdminController::new

book_edit:
    path: admin/book/{id}/edit
    controller: App\Controller\BookAdminController::edit

new_author:
   path: admin/author/new
   controller: App\Controller\AuthorAdminController::newAuthor

new_genre:
  path: admin/genre/new
  controller: App\Controller\GenreAdminController::newGenre

show_genre:
    path: /Genre
    controller: App\Controller\GenreController::showGenre

genre_books:
    path: /genre/{slug}
    controller: App\Controller\GenreController::showBooks
