index:
    path: /
    controller: App\Controller\BookController::homepage

bookView:
    path: /book/{slug}
    controller: App\Controller\BookController::show

bookList:
    path: /admin/book/list
    controller: App\Controller\BookAdminController::list

new:
    path: admin/book/new
    controller: App\Controller\BookAdminController::new

edit:
    path: admin/book/{id}/edit
    controller: App\Controller\BookAdminController::edit

newauthor:
   path: admin/author/new
   controller: App\Controller\AuthorAdminController::newauthor

newgenre:
  path: admin/genre/new
  controller: App\Controller\GenreAdminController::newgenre

showGenre:
    path: /Genre
    controller: App\Controller\GenreController::showGenre

genreBooks:
    path: /genre/{slug}
    controller: App\Controller\GenreController::showBooks

uploadTest:
    path: /admin/upload/test
    controller: App\Controller\BookAdminController::temporaryUploadAction